### ISSUE TITLE
Can't install it :-(

### ISSUE THREAD

**Issue by ServusJon** [robertbtown/BtownToolkit#1]
My current deployment target is 9.0. Even tried higher ones :-(

[!] Unable to satisfy the following requirements:

- `BtownToolkit` required by `Podfile`

Specs satisfying the `BtownToolkit` dependency were found, but they required a higher minimum deployment target.

**Comment by yepp85** [comment]
Hi @ServusJon 
I will look into this. I forgot to check this issues page for some time :)

**Comment by ServusJon** [comment]
Thanks Mate :-)
